remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin    : "air" #  "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale                   : "en-US"
url                      : "https://fortress64.github.io/"
baseurl                  : "/"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
plugins:
  - jekyll-include-cache
