remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin    : "air" #  "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-include-cache
